### ISSUE TITLE
 ERROR: Version in "./docker-compose.yml" is unsupported.

### ISSUE THREAD

**Issue by PandaWhisperer** [stefa2k/prysm-docker-compose#14]
I'm getting this error when trying to run any of the YAML files with `docker-compose up`:

```
ERROR: Version in "./docker-compose.yaml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

I'm running Ubuntu 18.04 LTS with the following Docker versions:

```
$ docker --version
Docker version 19.03.8, build afacb8b7f0
$ docker-compose --version
docker-compose version 1.17.1, build unknown
```

I've consulted https://docs.docker.com/compose/compose-file/, which tells me my engine *should* support up to version 3.8 of the YAML file format, but for some reason it doesn't.

I've also tried to replace the version number in the file(s) with some random lower versions, but then I get errors about certain extensions (such as logging) not being supported.

**Comment by rhlsthrm** [comment]
I had this same issue and it disappeared when I installed the latest version of docker-compose.

**Comment by PandaWhisperer** [comment]
Thank @rhlsthrm. I just double checked, and version I have seems to be the most recent package available for my distribution.

**Comment by stefa2k** [comment]
Some linux distributions are - unfortunately - far behind when it comes to update their docker-compose package. I use also the instructions linked by @PandaWhisperer and although its not a very smooth solution it works well.

Due to features the `docker-compose.yaml` uses its not feasible to downgrade.
