### ISSUE TITLE
createAccounts.sh not working for Onyx testnet (alpha.10/alpha.11) 

### ISSUE THREAD

**Issue by PandaWhisperer** [stefa2k/prysm-docker-compose#15]
Hi, first of all, thanks for the great work on this setup! I've spun up two Prysm validator setups for Onyx, one with the `prysm.sh` script, and one with this setup. The former was easier, but this one seems more flexible.

However, the `createAccounts.sh` script wasn't working for me (I know it comes without warranty!), so I took some time to figure out why. This is what I found:

1. First of all, the deposit contract address (`$BEACON_CONTRACT` in `createAccounts.sh`) is wrong. I believe this is the address for the now-defunct Topaz network). It should be `0x0F0F0fc0530007361933EaB5DB97d09aCDD6C1c8` for Onyx.
2. Even after changing the address, all the deposit transactions fail because they don't include the depositdata. This is because it's not properly extracted from the tempfile. Could be because of changes in Prysm, but the data is now located on line 8 instead of line 9. Changing `createAccounts.sh:13` to `RAWTXDATA=$(sed -n 8,1p /tmp/validatorcreateoutput | tr -d '\r')` fixes this.
3. Even with the deposit address and depositdata correct, *some* transactions (about 5% or so) fail due to running out of gas. Members of the Prysm Discord suggested setting the gas limit to 400,000 to avoid this.

I've forked the repo and will send you a pull request with the suggest changes.

**Comment by stefa2k** [comment]
Nice work! Looking forward to your pull request

Side node: I'm building more flexible and easier-to-use ansible playbooks for all steps, including installation of this repo, loading your validators with ETH with correct gas, correct contract, ... This should make it way easier to setup: https://github.com/stefa2k/prysm-ansible
