### ISSUE TITLE
Update release tag for alpha.12

### ISSUE THREAD

**Issue by PandaWhisperer** [stefa2k/prysm-docker-compose#20]
Hi, looks like the latest stable release tag is `alpha.12`. 

The git commit hash is `802bdf5`, and the corresponding Docker tag is `HEAD-802bdf`. 

I've put this in my `.env` file and it seems to work fine.

The validator still reports being `alpha.11`, but the corresponding commit hash seems to be correct:

```
$ docker-compose exec validator /app/validator/image.binary --version
validator version Prysm/v1.0.0-alpha.11/802bdf5561a8c713fc2a8ae5b16cdb02b192e94a. Built at: 2020-06-17 18:50:29+00:00
```

vs.

```
$ prysm.sh validator --version
Starting Prysm validator --version
validator version Prysm/v1.0.0-alpha.12/802bdf5561a8c713fc2a8ae5b16cdb02b192e94a. Built at: 2020-06-17 18:58:22+00:00
```

**Comment by stefa2k** [comment]
Current tag in `.env` file is `HEAD-1dfeb6`:
```
2020/06/19 07:55:04 maxprocs: Leaving GOMAXPROCS=2: CPU quota undefined
beacon-chain version Prysm/v1.0.0-alpha.12/340ddf20cbde5aacbb511ab104035a802396af74. Built at: 2020-06-18 04:41:53+00:00
```

lgtm

**Comment by PandaWhisperer** [comment]
You mean `HEAD-340ddf`, right? 

https://github.com/stefa2k/prysm-docker-compose/commit/74823cd797eed32929ae1c277ce87c0b32e342ff

**Comment by stefa2k** [comment]
You're right, I committed it on the wrong branch, now its the given docker tag: https://github.com/stefa2k/prysm-docker-compose/blob/master/.env

**Comment by PandaWhisperer** [comment]
Okay, thanks. I'll go ahead and close this, but this has raised a new issue for me: how to keep local configuration changes separate from upstream changes, so I can still `git pull` updates.

For instance, the `.env` file contains my local password, so it will block merging in new changes. I'll make a new issue to discuss this problem (and potential solutions).
