### ISSUE TITLE
Infura configuration for prysm-no-geth

### ISSUE THREAD

**Issue by gwenvador** [stefa2k/prysm-docker-compose#45]
I wonder how to configure an infura endpoint when launching prysm with no geth configuration. Does prysm point by default to https://goerli.prylabs.net?
Should you add http-web3provider in beacon-no-geth.yaml?

**Comment by stefa2k** [comment]
Thanks for your inquery!

Prysm's default setting for `http-web3provider` points to `https://goerli.prylabs.net`.

Using infura is as simple as using the same flag [here](https://github.com/stefa2k/prysm-docker-compose/blob/master/config/beacon.yaml#L29) and replacing the endpoint with your infura url.

**Comment by gwenvador** [comment]
Yes thanks for the confirmation. Maybe that could help for the README to be more explicit on how to use the no geth configuration. For mainnet will Prysm also use a default web3provider?

**Comment by stefa2k** [comment]
https://github.com/stefa2k/prysm-docker-compose#i-want-to-use-a-specific-ethereum-1-node
